include!("../src/lib.rs");

#[test]
fn test_1() {
    assert_eq!(Solution::decode_string("2[ab3[cd]]".to_string()), "abcdcdcdabcdcdcd".to_string());
}

#[test]
fn test_2() {
    assert_eq!(Solution::decode_string("2[ab3[c]]".to_string()), "abcccabccc".to_string());
}

#[test]
fn test_3() {
    assert_eq!(Solution::decode_string("1[a1[b1[c]]]".to_string()), "abc".to_string());
}

#[test]
fn test_4() {
    assert_eq!(Solution::decode_string("2[3[a]]".to_string()), "aaaaaa".to_string());
}

#[test]
fn test_5() {
    assert_eq!(Solution::decode_string("a1[b]".to_string()), "ab".to_string());
}

#[test]
fn test_6() {
    assert_eq!(Solution::decode_string("3[a3[b]1[c]]".to_string()), "abbbcabbbcabbbc".to_string());
}

#[test]
fn test_7() {
    assert_eq!(Solution::decode_string("a".to_string()), "a".to_string());
}

#[test]
fn test_8() {
    assert_eq!(Solution::decode_string("10[abc]".to_string()), "abcabcabcabcabcabcabcabcabcabc".to_string());
}

#[test]
fn test_9() {
    assert_eq!(Solution::decode_string("1[2[3[4[a]]]]".to_string()), "aaaaaaaaaaaaaaaaaaaaaaaa".to_string());
}

#[test]
fn test_10() {
    assert_eq!(Solution::decode_string("2[3[a]b]".to_string()), "aaabaaab".to_string());
}

#[test]
fn test_11() {
    assert_eq!(Solution::decode_string("4[ab]".to_string()), "abababab".to_string());
}

#[test]
fn test_12() {
    assert_eq!(Solution::decode_string("1[a2[b3[c]]]".to_string()), "abcccbccc".to_string());
}

#[test]
fn test_13() {
    assert_eq!(Solution::decode_string("10[a]".to_string()), "aaaaaaaaaa".to_string());
}

#[test]
fn test_14() {
    assert_eq!(Solution::decode_string("a2[b]c".to_string()), "abbc".to_string());
}

#[test]
fn test_15() {
    assert_eq!(Solution::decode_string("2[abc]3[cd]ef".to_string()), "abcabccdcdcdef".to_string());
}

#[test]
fn test_16() {
    assert_eq!(Solution::decode_string("1[a]".to_string()), "a".to_string());
}

#[test]
fn test_17() {
    assert_eq!(Solution::decode_string("3[a2[c]]".to_string()), "accaccacc".to_string());
}

#[test]
fn test_18() {
    assert_eq!(Solution::decode_string("3[a]2[bc]".to_string()), "aaabcbc".to_string());
}

#[test]
fn test_19() {
    assert_eq!(Solution::decode_string("abc".to_string()), "abc".to_string());
}

#[test]
fn test_20() {
    assert_eq!(Solution::decode_string("3[a3[b2[c]]]".to_string()), "abccbccbccabccbccbccabccbccbcc".to_string());
}

#[test]
fn test_21() {
    assert_eq!(Solution::decode_string("100[ab]".to_string()), "abababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababab".to_string());
}

#[test]
fn test_22() {
    assert_eq!(Solution::decode_string("a[b]".to_string()), "a".to_string());
}

#[test]
fn test_23() {
    assert_eq!(Solution::decode_string("2[b3[c]]".to_string()), "bcccbccc".to_string());
}

#[test]
fn test_24() {
    assert_eq!(Solution::decode_string("1[xyz]2[uvw]".to_string()), "xyzuvwuvw".to_string());
}

#[test]
fn test_25() {
    assert_eq!(Solution::decode_string("a2[b3[c]]".to_string()), "abcccbccc".to_string());
}

#[test]
fn test_26() {
    assert_eq!(Solution::decode_string("1[a1[b]]".to_string()), "ab".to_string());
}

#[test]
fn test_27() {
    assert_eq!(Solution::decode_string("4[3[z]2[y]]".to_string()), "zzzyyzzzyyzzzyyzzzyy".to_string());
}

#[test]
fn test_28() {
    assert_eq!(Solution::decode_string("5[ab3[c2[d]]]".to_string()), "abcddcddcddabcddcddcddabcddcddcddabcddcddcddabcddcddcdd".to_string());
}

#[test]
fn test_29() {
    assert_eq!(Solution::decode_string("5[a1[b2[c3[d4[e]]]]]".to_string()), "abcdeeeedeeeedeeeecdeeeedeeeedeeeeabcdeeeedeeeedeeeecdeeeedeeeedeeeeabcdeeeedeeeedeeeecdeeeedeeeedeeeeabcdeeeedeeeedeeeecdeeeedeeeedeeeeabcdeeeedeeeedeeeecdeeeedeeeedeeee".to_string());
}

#[test]
fn test_30() {
    assert_eq!(Solution::decode_string("a2[b3[c4[d5[e6[f7[g]]]]]]".to_string()), "abcdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggcdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggcdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggbcdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggcdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggcdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggdefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfgggggggefgggggggfgggggggfgggggggfgggggggfgggggggfggggggg".to_string());
}

#[test]
fn test_31() {
    assert_eq!(Solution::decode_string("abc3[d2[e1[f]]]".to_string()), "abcdefefdefefdefef".to_string());
}

#[test]
fn test_32() {
    assert_eq!(Solution::decode_string("5[a2[b3[c4[d]]]]".to_string()), "abcddddcddddcddddbcddddcddddcddddabcddddcddddcddddbcddddcddddcddddabcddddcddddcddddbcddddcddddcddddabcddddcddddcddddbcddddcddddcddddabcddddcddddcddddbcddddcddddcdddd".to_string());
}

#[test]
fn test_33() {
    assert_eq!(Solution::decode_string("3[2[mn]1[op]2[qr]]".to_string()), "mnmnopqrqrmnmnopqrqrmnmnopqrqr".to_string());
}

#[test]
fn test_34() {
    assert_eq!(Solution::decode_string("5[c2[d]]".to_string()), "cddcddcddcddcdd".to_string());
}

#[test]
fn test_35() {
    assert_eq!(Solution::decode_string("a1[b2[c3[d]]]".to_string()), "abcdddcddd".to_string());
}

#[test]
fn test_36() {
    assert_eq!(Solution::decode_string("7[2[x]3[y]]".to_string()), "xxyyyxxyyyxxyyyxxyyyxxyyyxxyyyxxyyy".to_string());
}

#[test]
fn test_37() {
    assert_eq!(Solution::decode_string("2[ab3[cd]]4[ef5[gh]]".to_string()), "abcdcdcdabcdcdcdefghghghghghefghghghghghefghghghghghefghghghghgh".to_string());
}

#[test]
fn test_38() {
    assert_eq!(Solution::decode_string("3[ab2[c]]4[de]".to_string()), "abccabccabccdededede".to_string());
}

#[test]
fn test_39() {
    assert_eq!(Solution::decode_string("4[ab3[c2[d]]]".to_string()), "abcddcddcddabcddcddcddabcddcddcddabcddcddcdd".to_string());
}

#[test]
fn test_40() {
    assert_eq!(Solution::decode_string("3[a2[b1[c0[d]]]]".to_string()), "abcbcabcbcabcbc".to_string());
}

#[test]
fn test_41() {
    assert_eq!(Solution::decode_string("3[a4[b5[c6[d7[e8[f]]]]]]".to_string()), "abcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffbcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffbcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffbcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffabcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffbcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffbcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffbcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffabcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffbcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffbcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffbcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffcdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffdeffffffffeffffffffeffffffffeffffffffeffffffffeffffffffeffffffff".to_string());
}

#[test]
fn test_42() {
    assert_eq!(Solution::decode_string("3[2[a]1[b]]2[3[c]4[d]]".to_string()), "aabaabaabcccddddcccdddd".to_string());
}

#[test]
fn test_43() {
    assert_eq!(Solution::decode_string("abc2[def3[ghi]]jkl4[mno5[pqr]]stu".to_string()), "abcdefghighighidefghighighijklmnopqrpqrpqrpqrpqrmnopqrpqrpqrpqrpqrmnopqrpqrpqrpqrpqrmnopqrpqrpqrpqrpqrstu".to_string());
}

#[test]
fn test_44() {
    assert_eq!(Solution::decode_string("2[3[a]2[b3[c]2[d]]]".to_string()), "aaabcccddbcccddaaabcccddbcccdd".to_string());
}

#[test]
fn test_45() {
    assert_eq!(Solution::decode_string("6[ab2[cd3[ef]]]".to_string()), "abcdefefefcdefefefabcdefefefcdefefefabcdefefefcdefefefabcdefefefcdefefefabcdefefefcdefefefabcdefefefcdefefef".to_string());
}

#[test]
fn test_46() {
    assert_eq!(Solution::decode_string("7[fg]2[h3[i]]".to_string()), "fgfgfgfgfgfgfghiiihiii".to_string());
}

#[test]
fn test_47() {
    assert_eq!(Solution::decode_string("7[x2[y3[z4[w]]]]".to_string()), "xyzwwwwzwwwwzwwwwyzwwwwzwwwwzwwwwxyzwwwwzwwwwzwwwwyzwwwwzwwwwzwwwwxyzwwwwzwwwwzwwwwyzwwwwzwwwwzwwwwxyzwwwwzwwwwzwwwwyzwwwwzwwwwzwwwwxyzwwwwzwwwwzwwwwyzwwwwzwwwwzwwwwxyzwwwwzwwwwzwwwwyzwwwwzwwwwzwwwwxyzwwwwzwwwwzwwwwyzwwwwzwwwwzwwww".to_string());
}

#[test]
fn test_48() {
    assert_eq!(Solution::decode_string("5[2[x3[y]]4[z]]".to_string()), "xyyyxyyyzzzzxyyyxyyyzzzzxyyyxyyyzzzzxyyyxyyyzzzzxyyyxyyyzzzz".to_string());
}

#[test]
fn test_49() {
    assert_eq!(Solution::decode_string("6[ab2[cd3[ef4[gh]]]]".to_string()), "abcdefghghghghefghghghghefghghghghcdefghghghghefghghghghefghghghghabcdefghghghghefghghghghefghghghghcdefghghghghefghghghghefghghghghabcdefghghghghefghghghghefghghghghcdefghghghghefghghghghefghghghghabcdefghghghghefghghghghefghghghghcdefghghghghefghghghghefghghghghabcdefghghghghefghghghghefghghghghcdefghghghghefghghghghefghghghghabcdefghghghghefghghghghefghghghghcdefghghghghefghghghghefghghghgh".to_string());
}

#[test]
fn test_50() {
    assert_eq!(Solution::decode_string("2[x2[y3[z]]]1[a]".to_string()), "xyzzzyzzzxyzzzyzzza".to_string());
}

#[test]
fn test_51() {
    assert_eq!(Solution::decode_string("7[z]6[y5[x4[w3[v2[u1[t]]]]]]".to_string()), "zzzzzzzyxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututyxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututyxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututyxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututyxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututyxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvututxwvututvututvututwvututvututvututwvututvututvututwvututvututvutut".to_string());
}

#[test]
fn test_52() {
    assert_eq!(Solution::decode_string("2[a3[b4[c]]]".to_string()), "abccccbccccbccccabccccbccccbcccc".to_string());
}

#[test]
fn test_53() {
    assert_eq!(Solution::decode_string("10[a9[bc3[de]]]".to_string()), "abcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdededeabcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdededeabcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdededeabcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdededeabcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdededeabcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdededeabcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdededeabcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdededeabcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdededeabcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdededebcdedede".to_string());
}

#[test]
fn test_54() {
    assert_eq!(Solution::decode_string("3[ab]4[cd]5[ef]".to_string()), "abababcdcdcdcdefefefefef".to_string());
}

#[test]
fn test_55() {
    assert_eq!(Solution::decode_string("10[ab]".to_string()), "abababababababababab".to_string());
}

#[test]
fn test_56() {
    assert_eq!(Solution::decode_string("5[4[3[2[1[x]]]]]".to_string()), "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx".to_string());
}

#[test]
fn test_57() {
    assert_eq!(Solution::decode_string("2[ab3[cd4[ef]]]".to_string()), "abcdefefefefcdefefefefcdefefefefabcdefefefefcdefefefefcdefefefef".to_string());
}

#[test]
fn test_58() {
    assert_eq!(Solution::decode_string("5[ab]3[cd]2[ef1[gh]]".to_string()), "abababababcdcdcdefghefgh".to_string());
}

#[test]
fn test_59() {
    assert_eq!(Solution::decode_string("7[2[pq]3[rs]]".to_string()), "pqpqrsrsrspqpqrsrsrspqpqrsrsrspqpqrsrsrspqpqrsrsrspqpqrsrsrspqpqrsrsrs".to_string());
}

#[test]
fn test_60() {
    assert_eq!(Solution::decode_string("2[3[a]b]4[c5[d]]".to_string()), "aaabaaabcdddddcdddddcdddddcddddd".to_string());
}

#[test]
fn test_61() {
    assert_eq!(Solution::decode_string("3[2[3[4[a]]]]".to_string()), "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".to_string());
}

#[test]
fn test_62() {
    assert_eq!(Solution::decode_string("6[2[a]3[b]]".to_string()), "aabbbaabbbaabbbaabbbaabbbaabbb".to_string());
}

#[test]
fn test_63() {
    assert_eq!(Solution::decode_string("2[abc3[def4[ghi5[jkl]]]]".to_string()), "abcdefghijkljkljkljkljklghijkljkljkljkljklghijkljkljkljkljklghijkljkljkljkljkldefghijkljkljkljkljklghijkljkljkljkljklghijkljkljkljkljklghijkljkljkljkljkldefghijkljkljkljkljklghijkljkljkljkljklghijkljkljkljkljklghijkljkljkljkljklabcdefghijkljkljkljkljklghijkljkljkljkljklghijkljkljkljkljklghijkljkljkljkljkldefghijkljkljkljkljklghijkljkljkljkljklghijkljkljkljkljklghijkljkljkljkljkldefghijkljkljkljkljklghijkljkljkljkljklghijkljkljkljkljklghijkljkljkljkljkl".to_string());
}

#[test]
fn test_64() {
    assert_eq!(Solution::decode_string("2[a3[b4[c5[d6[e]]]]]".to_string()), "abcdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeecdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeecdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeecdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeebcdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeecdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeecdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeecdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeebcdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeecdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeecdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeecdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeeabcdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeecdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeecdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeecdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeebcdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeecdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeecdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeecdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeebcdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeecdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeecdeeeeeedeeeeeedeeeeeedeeeeeedeeeeeecdeeeeeedeeeeeedeeeeeedeeeeeedeeeeee".to_string());
}

#[test]
fn test_65() {
    assert_eq!(Solution::decode_string("3[2[1[0[]]]]".to_string()), "".to_string());
}

#[test]
fn test_66() {
    assert_eq!(Solution::decode_string("10[f9[g]]".to_string()), "fgggggggggfgggggggggfgggggggggfgggggggggfgggggggggfgggggggggfgggggggggfgggggggggfgggggggggfggggggggg".to_string());
}

#[test]
fn test_67() {
    assert_eq!(Solution::decode_string("15[abc10[de]]".to_string()), "abcdedededededededededeabcdedededededededededeabcdedededededededededeabcdedededededededededeabcdedededededededededeabcdedededededededededeabcdedededededededededeabcdedededededededededeabcdedededededededededeabcdedededededededededeabcdedededededededededeabcdedededededededededeabcdedededededededededeabcdedededededededededeabcdededededededededede".to_string());
}

#[test]
fn test_68() {
    assert_eq!(Solution::decode_string("5[k9[l10[m]]]".to_string()), "klmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmklmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmklmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmklmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmklmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmmlmmmmmmmmmm".to_string());
}

#[test]
fn test_69() {
    assert_eq!(Solution::decode_string("5[xy2[z3[w4[v]]]]".to_string()), "xyzwvvvvwvvvvwvvvvzwvvvvwvvvvwvvvvxyzwvvvvwvvvvwvvvvzwvvvvwvvvvwvvvvxyzwvvvvwvvvvwvvvvzwvvvvwvvvvwvvvvxyzwvvvvwvvvvwvvvvzwvvvvwvvvvwvvvvxyzwvvvvwvvvvwvvvvzwvvvvwvvvvwvvvv".to_string());
}

#[test]
fn test_70() {
    assert_eq!(Solution::decode_string("1[1[1[1[ab]]]]".to_string()), "ab".to_string());
}

#[test]
fn test_71() {
    assert_eq!(Solution::decode_string("5[1[2[3[4[5[a]]]]]]".to_string()), "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".to_string());
}

#[test]
fn test_72() {
    assert_eq!(Solution::decode_string("4[ab2[c]]".to_string()), "abccabccabccabcc".to_string());
}

#[test]
fn test_73() {
    assert_eq!(Solution::decode_string("4[a2[b3[c]]]".to_string()), "abcccbcccabcccbcccabcccbcccabcccbccc".to_string());
}

#[test]
fn test_74() {
    assert_eq!(Solution::decode_string("2[x3[y4[z]]]".to_string()), "xyzzzzyzzzzyzzzzxyzzzzyzzzzyzzzz".to_string());
}

#[test]
fn test_75() {
    assert_eq!(Solution::decode_string("3[2[3[4[a]]]5[b]]".to_string()), "aaaaaaaaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaaaaaaaabbbbb".to_string());
}

#[test]
fn test_76() {
    assert_eq!(Solution::decode_string("10[ab2[cd]ef3[gh]]".to_string()), "abcdcdefghghghabcdcdefghghghabcdcdefghghghabcdcdefghghghabcdcdefghghghabcdcdefghghghabcdcdefghghghabcdcdefghghghabcdcdefghghghabcdcdefghghgh".to_string());
}

#[test]
fn test_77() {
    assert_eq!(Solution::decode_string("5[abc2[def]]".to_string()), "abcdefdefabcdefdefabcdefdefabcdefdefabcdefdef".to_string());
}

#[test]
fn test_78() {
    assert_eq!(Solution::decode_string("3[2[3[a2[b]]]]".to_string()), "abbabbabbabbabbabbabbabbabbabbabbabbabbabbabbabbabbabb".to_string());
}

#[test]
fn test_79() {
    assert_eq!(Solution::decode_string("2[3[ab]]".to_string()), "abababababab".to_string());
}

#[test]
fn test_80() {
    assert_eq!(Solution::decode_string("3[xy2[z]]2[ab]".to_string()), "xyzzxyzzxyzzabab".to_string());
}

#[test]
fn test_81() {
    assert_eq!(Solution::decode_string("10[1[a]2[b]3[c]4[d]5[e]]".to_string()), "abbcccddddeeeeeabbcccddddeeeeeabbcccddddeeeeeabbcccddddeeeeeabbcccddddeeeeeabbcccddddeeeeeabbcccddddeeeeeabbcccddddeeeeeabbcccddddeeeeeabbcccddddeeeee".to_string());
}

#[test]
fn test_82() {
    assert_eq!(Solution::decode_string("3[2[3[4[x]]]]".to_string()), "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx".to_string());
}

#[test]
fn test_83() {
    assert_eq!(Solution::decode_string("2[3[a]b4[c]]".to_string()), "aaabccccaaabcccc".to_string());
}

#[test]
fn test_84() {
    assert_eq!(Solution::decode_string("10[x]".to_string()), "xxxxxxxxxx".to_string());
}

#[test]
fn test_85() {
    assert_eq!(Solution::decode_string("4[2[xy]z]".to_string()), "xyxyzxyxyzxyxyzxyxyz".to_string());
}

#[test]
fn test_86() {
    assert_eq!(Solution::decode_string("6[a5[b4[c3[d2[e1[f]]]]]]".to_string()), "abcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefabcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefabcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefabcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefabcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefabcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefbcdefefdefefdefefcdefefdefefdefefcdefefdefefdefefcdefefdefefdefef".to_string());
}

#[test]
fn test_87() {
    assert_eq!(Solution::decode_string("4[x5[yz]w]".to_string()), "xyzyzyzyzyzwxyzyzyzyzyzwxyzyzyzyzyzwxyzyzyzyzyzw".to_string());
}

#[test]
fn test_88() {
    assert_eq!(Solution::decode_string("4[3[2[b1[c]]]]".to_string()), "bcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbcbc".to_string());
}

#[test]
fn test_89() {
    assert_eq!(Solution::decode_string("2[x3[xy4[z]]]".to_string()), "xxyzzzzxyzzzzxyzzzzxxyzzzzxyzzzzxyzzzz".to_string());
}

#[test]
fn test_90() {
    assert_eq!(Solution::decode_string("2[3[a2[b]]c]".to_string()), "abbabbabbcabbabbabbc".to_string());
}

#[test]
fn test_91() {
    assert_eq!(Solution::decode_string("9[abc]8[def]7[ghi]".to_string()), "abcabcabcabcabcabcabcabcabcdefdefdefdefdefdefdefdefghighighighighighighi".to_string());
}

#[test]
fn test_92() {
    assert_eq!(Solution::decode_string("4[ab]5[cd]".to_string()), "ababababcdcdcdcdcd".to_string());
}

#[test]
fn test_93() {
    assert_eq!(Solution::decode_string("2[3[xy]z]".to_string()), "xyxyxyzxyxyxyz".to_string());
}

#[test]
fn test_94() {
    assert_eq!(Solution::decode_string("4[x3[y2[z]]]".to_string()), "xyzzyzzyzzxyzzyzzyzzxyzzyzzyzzxyzzyzzyzz".to_string());
}

#[test]
fn test_95() {
    assert_eq!(Solution::decode_string("3[2[a]b]".to_string()), "aabaabaab".to_string());
}

#[test]
fn test_96() {
    assert_eq!(Solution::decode_string("abc2[3[de]fg]".to_string()), "abcdededefgdededefg".to_string());
}

#[test]
fn test_97() {
    assert_eq!(Solution::decode_string("1[abc2[def3[ghi]]]".to_string()), "abcdefghighighidefghighighi".to_string());
}

#[test]
fn test_98() {
    assert_eq!(Solution::decode_string("2[abc2[def3[ghi]]]".to_string()), "abcdefghighighidefghighighiabcdefghighighidefghighighi".to_string());
}

#[test]
fn test_99() {
    assert_eq!(Solution::decode_string("1[2[3[4[5[a]]]]]".to_string()), "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".to_string());
}

#[test]
fn test_100() {
    assert_eq!(Solution::decode_string("5[ab3[cd]]".to_string()), "abcdcdcdabcdcdcdabcdcdcdabcdcdcdabcdcdcd".to_string());
}

#[test]
fn test_101() {
    assert_eq!(Solution::decode_string("2[x3[y4[z]]]1[w]".to_string()), "xyzzzzyzzzzyzzzzxyzzzzyzzzzyzzzzw".to_string());
}

#[test]
fn test_102() {
    assert_eq!(Solution::decode_string("7[2[a]3[b]]".to_string()), "aabbbaabbbaabbbaabbbaabbbaabbbaabbb".to_string());
}

#[test]
fn test_103() {
    assert_eq!(Solution::decode_string("9[8[7[6[5[4[3[2[1[0[a]]]]]]]]]]".to_string()), "".to_string());
}

#[test]
fn test_104() {
    assert_eq!(Solution::decode_string("4[x5[y]]".to_string()), "xyyyyyxyyyyyxyyyyyxyyyyy".to_string());
}

#[test]
fn test_105() {
    assert_eq!(Solution::decode_string("2[abc3[def4[ghi]]]".to_string()), "abcdefghighighighidefghighighighidefghighighighiabcdefghighighighidefghighighighidefghighighighi".to_string());
}

#[test]
fn test_106() {
    assert_eq!(Solution::decode_string("5[ab2[c]]3[xy]2[de]".to_string()), "abccabccabccabccabccxyxyxydede".to_string());
}

#[test]
fn test_107() {
    assert_eq!(Solution::decode_string("5[abc2[de]]".to_string()), "abcdedeabcdedeabcdedeabcdedeabcdede".to_string());
}

#[test]
fn test_108() {
    assert_eq!(Solution::decode_string("7[k2[3[xyz]]]".to_string()), "kxyzxyzxyzxyzxyzxyzkxyzxyzxyzxyzxyzxyzkxyzxyzxyzxyzxyzxyzkxyzxyzxyzxyzxyzxyzkxyzxyzxyzxyzxyzxyzkxyzxyzxyzxyzxyzxyzkxyzxyzxyzxyzxyzxyz".to_string());
}

#[test]
fn test_109() {
    assert_eq!(Solution::decode_string("1[abc2[def]]".to_string()), "abcdefdef".to_string());
}

#[test]
fn test_110() {
    assert_eq!(Solution::decode_string("2[3[4[5[6[7[8[9[0[1[a]]]]]]]]]]".to_string()), "".to_string());
}

#[test]
fn test_111() {
    assert_eq!(Solution::decode_string("3[2[1[x]]]".to_string()), "xxxxxx".to_string());
}

#[test]
fn test_112() {
    assert_eq!(Solution::decode_string("5[ab2[cd]]".to_string()), "abcdcdabcdcdabcdcdabcdcdabcdcd".to_string());
}

#[test]
fn test_113() {
    assert_eq!(Solution::decode_string("6[5[4[3[2[1[a]]]]]]".to_string()), "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".to_string());
}

#[test]
fn test_114() {
    assert_eq!(Solution::decode_string("7[xyz]3[abc2[def1[ghi]]]".to_string()), "xyzxyzxyzxyzxyzxyzxyzabcdefghidefghiabcdefghidefghiabcdefghidefghi".to_string());
}

#[test]
fn test_115() {
    assert_eq!(Solution::decode_string("x1[y2[z3[a4[b5[c]]]]]".to_string()), "xyzabcccccbcccccbcccccbcccccabcccccbcccccbcccccbcccccabcccccbcccccbcccccbccccczabcccccbcccccbcccccbcccccabcccccbcccccbcccccbcccccabcccccbcccccbcccccbccccc".to_string());
}

#[test]
fn test_116() {
    assert_eq!(Solution::decode_string("3[ab2[c3[d]]]".to_string()), "abcdddcdddabcdddcdddabcdddcddd".to_string());
}

#[test]
fn test_117() {
    assert_eq!(Solution::decode_string("6[a2[b3[c4[d]]]]".to_string()), "abcddddcddddcddddbcddddcddddcddddabcddddcddddcddddbcddddcddddcddddabcddddcddddcddddbcddddcddddcddddabcddddcddddcddddbcddddcddddcddddabcddddcddddcddddbcddddcddddcddddabcddddcddddcddddbcddddcddddcdddd".to_string());
}

#[test]
fn test_118() {
    assert_eq!(Solution::decode_string("15[a]".to_string()), "aaaaaaaaaaaaaaa".to_string());
}

#[test]
fn test_119() {
    assert_eq!(Solution::decode_string("5[2[3[a]]]".to_string()), "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".to_string());
}

#[test]
fn test_120() {
    assert_eq!(Solution::decode_string("2[xy3[z]]4[ab]".to_string()), "xyzzzxyzzzabababab".to_string());
}

#[test]
fn test_121() {
    assert_eq!(Solution::decode_string("1[a2[b3[c4[d5[e]]]]]".to_string()), "abcdeeeeedeeeeedeeeeedeeeeecdeeeeedeeeeedeeeeedeeeeecdeeeeedeeeeedeeeeedeeeeebcdeeeeedeeeeedeeeeedeeeeecdeeeeedeeeeedeeeeedeeeeecdeeeeedeeeeedeeeeedeeeee".to_string());
}

#[test]
fn test_122() {
    assert_eq!(Solution::decode_string("4[a3[b]]".to_string()), "abbbabbbabbbabbb".to_string());
}

#[test]
fn test_123() {
    assert_eq!(Solution::decode_string("2[ab]3[cd]4[ef]".to_string()), "ababcdcdcdefefefef".to_string());
}

#[test]
fn test_124() {
    assert_eq!(Solution::decode_string("1[2[3[4[5[6[7[8[9[0[x]]]]]]]]]]".to_string()), "".to_string());
}

#[test]
fn test_125() {
    assert_eq!(Solution::decode_string("1[2[3[4[5[6[x]]]]]]".to_string()), "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx".to_string());
}

#[test]
fn test_126() {
    assert_eq!(Solution::decode_string("2[a3[b4[c5[d6[e7[f]]]]]]".to_string()), "abcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffbcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffbcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffabcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffbcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffbcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffcdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffffdefffffffefffffffefffffffefffffffefffffffefffffff".to_string());
}

#[test]
fn test_127() {
    assert_eq!(Solution::decode_string("4[a3[b2[c1[d]]]]".to_string()), "abcdcdbcdcdbcdcdabcdcdbcdcdbcdcdabcdcdbcdcdbcdcdabcdcdbcdcdbcdcd".to_string());
}

#[test]
fn test_128() {
    assert_eq!(Solution::decode_string("3[2[3[4[5[a]]]]]".to_string()), "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".to_string());
}

#[test]
fn test_129() {
    assert_eq!(Solution::decode_string("1[xyz]2[uvw]3[2[abc]3[def]]4[ghi]".to_string()), "xyzuvwuvwabcabcdefdefdefabcabcdefdefdefabcabcdefdefdefghighighighi".to_string());
}

#[test]
fn test_130() {
    assert_eq!(Solution::decode_string("3[xyz2[abc]4[def]]5[ghi]".to_string()), "xyzabcabcdefdefdefdefxyzabcabcdefdefdefdefxyzabcabcdefdefdefdefghighighighighi".to_string());
}

#[test]
fn test_131() {
    assert_eq!(Solution::decode_string("2[2[2[2[2[abc]]]]]".to_string()), "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc".to_string());
}

#[test]
fn test_132() {
    assert_eq!(Solution::decode_string("3[b2[c]1[d]]4[e]".to_string()), "bccdbccdbccdeeee".to_string());
}

#[test]
fn test_133() {
    assert_eq!(Solution::decode_string("a2[b3[c4[d5[e]]]]".to_string()), "abcdeeeeedeeeeedeeeeedeeeeecdeeeeedeeeeedeeeeedeeeeecdeeeeedeeeeedeeeeedeeeeebcdeeeeedeeeeedeeeeedeeeeecdeeeeedeeeeedeeeeedeeeeecdeeeeedeeeeedeeeeedeeeee".to_string());
}
